/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialog_staGraStyleSet.java
 *
 * Created on 2011-5-5, 10:21:19
 */
package levyflight;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import levyflight.Export.StatisticGraphGen;
import levyflight.Export.StatisticGraphGenSchema;

/**
 *
 * @author wu
 */
public class JDialog_staGraStyleSet extends javax.swing.JDialog
{

    final private StatisticGraphGenSchema schema_fre = new StatisticGraphGenSchema();
    final private StatisticGraphGenSchema schema_cumFre = new StatisticGraphGenSchema();
    private StatisticGraphGenSchema defaultSchema = schema_fre;
    EnvironmentParameter ep = null;

    /**
     * 设置统计图表样式
     * @param parent
     * @param ep
     */
    static void setStaGraStyle(java.awt.Frame parent, EnvironmentParameter ep)
    {
        JDialog_staGraStyleSet dialog = new JDialog_staGraStyleSet(parent, true, ep);
        dialog.setVisible(true);
    }

    /** Creates new form JDialog_staGraStyleSet */
    public JDialog_staGraStyleSet(java.awt.Frame parent, boolean modal, EnvironmentParameter EP)
    {
        super(parent, modal);
        initComponents();
        EP.graSchema_cumFrequency.copyTo(this.schema_cumFre);
        EP.graSchema_frequency.copyTo(this.schema_fre);
        this.ep = EP;
        this.refershItems();
    }

    public void refershItems()
    {
        if (this.jRadioButton_fre.isSelected())
        {
            this.jPanel_items.setBackground(new Color(240, 240, 255));
            defaultSchema = this.schema_fre;
        } else
        {
            this.jPanel_items.setBackground(new Color(240, 255, 240));
            defaultSchema = this.schema_cumFre;
        }
        if (defaultSchema.style == StatisticGraphGen.style_lineChart)
        {
            this.jComboBox_style.setSelectedIndex(0);
        } else
        {
            this.jComboBox_style.setSelectedIndex(1);
        }
        this.jLabel_axisColor.setBackground(this.defaultSchema.color_axis);
        this.jLabel_fillColor.setBackground(this.defaultSchema.color_fill);
        this.jLabel_lineColor.setBackground(this.defaultSchema.color_line);
        this.jSpinner_axisWidth.setValue(this.defaultSchema.axisLineWidth);
        this.jSpinner_lineWidth.setValue(this.defaultSchema.lineWidth);
        this.jSpinner_dotRadius.setValue(this.defaultSchema.dotRadius);
        this.jCheckBox_lineSmooth.setSelected(this.defaultSchema.isUseLineSmoothStyle);
        this.jCheckBox_XLog.setSelected(this.defaultSchema.isXAxisLogStyle);
        this.jCheckBox_YLog.setSelected(this.defaultSchema.isYAxisLogStyle);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_item = new javax.swing.ButtonGroup();
        jRadioButton_cumFre = new javax.swing.JRadioButton();
        jRadioButton_fre = new javax.swing.JRadioButton();
        jPanel_items = new javax.swing.JPanel();
        jComboBox_style = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_axisColor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_lineColor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_fillColor = new javax.swing.JLabel();
        jCheckBox_YLog = new javax.swing.JCheckBox();
        jCheckBox_lineSmooth = new javax.swing.JCheckBox();
        jCheckBox_XLog = new javax.swing.JCheckBox();
        SpinnerNumberModel mode3=new SpinnerNumberModel();
        mode3.setMaximum(10.0);
        mode3.setMinimum(0.5);
        mode3.setStepSize(0.1);
        mode3.setValue(1.0);
        jSpinner_dotRadius = new JSpinner(mode3);
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SpinnerNumberModel mode=new SpinnerNumberModel();
        mode.setMaximum(3.0);
        mode.setMinimum(0.5);
        mode.setStepSize(0.1);
        mode.setValue(1.0);
        jSpinner_axisWidth = new JSpinner(mode);
        SpinnerNumberModel mode2=new SpinnerNumberModel();
        mode2.setMaximum(3.0);
        mode2.setMinimum(0.5);
        mode2.setStepSize(0.1);
        mode2.setValue(1.0);
        jSpinner_lineWidth = new JSpinner(mode2);
        jButton_cancel = new javax.swing.JButton();
        jButton_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(levyflight.LevyFlightApp.class).getContext().getResourceMap(JDialog_staGraStyleSet.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(518, 397));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        buttonGroup_item.add(jRadioButton_cumFre);
        jRadioButton_cumFre.setForeground(resourceMap.getColor("jRadioButton_cumFre.foreground")); // NOI18N
        jRadioButton_cumFre.setText(resourceMap.getString("jRadioButton_cumFre.text")); // NOI18N
        jRadioButton_cumFre.setName("jRadioButton_cumFre"); // NOI18N
        jRadioButton_cumFre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_cumFreActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_cumFre);
        jRadioButton_cumFre.setBounds(220, 20, 265, 23);

        buttonGroup_item.add(jRadioButton_fre);
        jRadioButton_fre.setForeground(resourceMap.getColor("jRadioButton_fre.foreground")); // NOI18N
        jRadioButton_fre.setSelected(true);
        jRadioButton_fre.setText(resourceMap.getString("jRadioButton_fre.text")); // NOI18N
        jRadioButton_fre.setName("jRadioButton_fre"); // NOI18N
        jRadioButton_fre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_freActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_fre);
        jRadioButton_fre.setBounds(10, 20, 199, 23);

        jPanel_items.setName("jPanel_items"); // NOI18N
        jPanel_items.setLayout(null);

        jComboBox_style.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Line plot", "Bar plot" }));
        jComboBox_style.setName("jComboBox_style"); // NOI18N
        jComboBox_style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_styleActionPerformed(evt);
            }
        });
        jPanel_items.add(jComboBox_style);
        jComboBox_style.setBounds(80, 20, 90, 21);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel_items.add(jLabel1);
        jLabel1.setBounds(20, 110, 66, 20);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel_items.add(jLabel2);
        jLabel2.setBounds(20, 20, 42, 20);

        jLabel_axisColor.setText(resourceMap.getString("jLabel_axisColor.text")); // NOI18N
        jLabel_axisColor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_axisColor.setName("jLabel_axisColor"); // NOI18N
        jLabel_axisColor.setOpaque(true);
        jLabel_axisColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_axisColorMouseClicked(evt);
            }
        });
        jPanel_items.add(jLabel_axisColor);
        jLabel_axisColor.setBounds(90, 60, 40, 20);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel_items.add(jLabel4);
        jLabel4.setBounds(190, 60, 66, 20);

        jLabel_lineColor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_lineColor.setName("jLabel_lineColor"); // NOI18N
        jLabel_lineColor.setOpaque(true);
        jLabel_lineColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_lineColorMouseClicked(evt);
            }
        });
        jPanel_items.add(jLabel_lineColor);
        jLabel_lineColor.setBounds(260, 60, 40, 20);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel_items.add(jLabel6);
        jLabel6.setBounds(340, 60, 66, 20);

        jLabel_fillColor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_fillColor.setName("jLabel_fillColor"); // NOI18N
        jLabel_fillColor.setOpaque(true);
        jLabel_fillColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_fillColorMouseClicked(evt);
            }
        });
        jPanel_items.add(jLabel_fillColor);
        jLabel_fillColor.setBounds(410, 60, 40, 20);

        jCheckBox_YLog.setText(resourceMap.getString("jCheckBox_YLog.text")); // NOI18N
        jCheckBox_YLog.setName("jCheckBox_YLog"); // NOI18N
        jCheckBox_YLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_YLogMouseClicked(evt);
            }
        });
        jPanel_items.add(jCheckBox_YLog);
        jCheckBox_YLog.setBounds(210, 200, 170, 23);

        jCheckBox_lineSmooth.setText(resourceMap.getString("jCheckBox_lineSmooth.text")); // NOI18N
        jCheckBox_lineSmooth.setName("jCheckBox_lineSmooth"); // NOI18N
        jCheckBox_lineSmooth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_lineSmoothMouseClicked(evt);
            }
        });
        jPanel_items.add(jCheckBox_lineSmooth);
        jCheckBox_lineSmooth.setBounds(20, 160, 170, 23);

        jCheckBox_XLog.setText(resourceMap.getString("jCheckBox_XLog.text")); // NOI18N
        jCheckBox_XLog.setName("jCheckBox_XLog"); // NOI18N
        jCheckBox_XLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_XLogMouseClicked(evt);
            }
        });
        jPanel_items.add(jCheckBox_XLog);
        jCheckBox_XLog.setBounds(20, 200, 170, 23);

        jSpinner_dotRadius.setName("jSpinner_dotRadius"); // NOI18N
        jSpinner_dotRadius.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_dotRadiusStateChanged(evt);
            }
        });
        jPanel_items.add(jSpinner_dotRadius);
        jSpinner_dotRadius.setBounds(410, 110, 50, 22);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel_items.add(jLabel8);
        jLabel8.setBounds(20, 60, 66, 20);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel_items.add(jLabel9);
        jLabel9.setBounds(190, 110, 66, 20);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel_items.add(jLabel10);
        jLabel10.setBounds(340, 110, 66, 20);

        jSpinner_axisWidth.setName("jSpinner_axisWidth"); // NOI18N
        jSpinner_axisWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_axisWidthStateChanged(evt);
            }
        });
        jPanel_items.add(jSpinner_axisWidth);
        jSpinner_axisWidth.setBounds(90, 110, 50, 22);

        jSpinner_lineWidth.setName("jSpinner_lineWidth"); // NOI18N
        jSpinner_lineWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_lineWidthStateChanged(evt);
            }
        });
        jPanel_items.add(jSpinner_lineWidth);
        jSpinner_lineWidth.setBounds(260, 110, 50, 22);

        getContentPane().add(jPanel_items);
        jPanel_items.setBounds(0, 60, 500, 240);

        jButton_cancel.setText(resourceMap.getString("jButton_cancel.text")); // NOI18N
        jButton_cancel.setName("jButton_cancel"); // NOI18N
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cancel);
        jButton_cancel.setBounds(420, 320, 69, 23);

        jButton_ok.setText(resourceMap.getString("jButton_ok.text")); // NOI18N
        jButton_ok.setName("jButton_ok"); // NOI18N
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ok);
        jButton_ok.setBounds(330, 320, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_styleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox_styleActionPerformed
    {//GEN-HEADEREND:event_jComboBox_styleActionPerformed

        int i = this.jComboBox_style.getSelectedIndex();
        if (i == 0)
        {
            this.defaultSchema.style = StatisticGraphGen.style_lineChart;
        } else if (i == 1)
        {
            this.defaultSchema.style = StatisticGraphGen.style_histgram;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_styleActionPerformed

    private void jLabel_axisColorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel_axisColorMouseClicked
    {//GEN-HEADEREND:event_jLabel_axisColorMouseClicked
        this.jLabel_axisColor.setBackground(JColorChooser.showDialog(null, "select axis color", this.jLabel_axisColor.getBackground()));
        this.defaultSchema.color_axis = this.jLabel_axisColor.getBackground();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_axisColorMouseClicked

    private void jLabel_lineColorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel_lineColorMouseClicked
    {//GEN-HEADEREND:event_jLabel_lineColorMouseClicked
        this.jLabel_lineColor.setBackground(JColorChooser.showDialog(null, "select axis color", this.jLabel_lineColor.getBackground()));
        this.defaultSchema.color_line = this.jLabel_lineColor.getBackground();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_lineColorMouseClicked

    private void jLabel_fillColorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel_fillColorMouseClicked
    {//GEN-HEADEREND:event_jLabel_fillColorMouseClicked
        this.jLabel_fillColor.setBackground(JColorChooser.showDialog(null, "select axis color", this.jLabel_fillColor.getBackground()));
        this.defaultSchema.color_fill = this.jLabel_fillColor.getBackground();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_fillColorMouseClicked

    private void jSpinner_axisWidthStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSpinner_axisWidthStateChanged
    {//GEN-HEADEREND:event_jSpinner_axisWidthStateChanged
        this.defaultSchema.axisLineWidth = (Double) this.jSpinner_axisWidth.getValue();
    }//GEN-LAST:event_jSpinner_axisWidthStateChanged

    private void jSpinner_lineWidthStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSpinner_lineWidthStateChanged
    {//GEN-HEADEREND:event_jSpinner_lineWidthStateChanged
        this.defaultSchema.lineWidth = (Double) this.jSpinner_lineWidth.getValue();
    }//GEN-LAST:event_jSpinner_lineWidthStateChanged

    private void jSpinner_dotRadiusStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSpinner_dotRadiusStateChanged
    {//GEN-HEADEREND:event_jSpinner_dotRadiusStateChanged
        this.defaultSchema.dotRadius = (Double) this.jSpinner_dotRadius.getValue();
    }//GEN-LAST:event_jSpinner_dotRadiusStateChanged

    private void jCheckBox_lineSmoothMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCheckBox_lineSmoothMouseClicked
    {//GEN-HEADEREND:event_jCheckBox_lineSmoothMouseClicked
        this.defaultSchema.isUseLineSmoothStyle = this.jCheckBox_lineSmooth.isSelected();
    }//GEN-LAST:event_jCheckBox_lineSmoothMouseClicked

    private void jCheckBox_XLogMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCheckBox_XLogMouseClicked
    {//GEN-HEADEREND:event_jCheckBox_XLogMouseClicked
        this.defaultSchema.isXAxisLogStyle = this.jCheckBox_XLog.isSelected();
    }//GEN-LAST:event_jCheckBox_XLogMouseClicked

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_okActionPerformed
    {//GEN-HEADEREND:event_jButton_okActionPerformed
        this.schema_cumFre.copyTo(this.ep.graSchema_cumFrequency);
        this.schema_fre.copyTo(this.ep.graSchema_frequency);
        this.dispose();
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_cancelActionPerformed
    {//GEN-HEADEREND:event_jButton_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jRadioButton_freActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton_freActionPerformed
    {//GEN-HEADEREND:event_jRadioButton_freActionPerformed
        this.refershItems();
    }//GEN-LAST:event_jRadioButton_freActionPerformed

    private void jRadioButton_cumFreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton_cumFreActionPerformed
    {//GEN-HEADEREND:event_jRadioButton_cumFreActionPerformed
        this.refershItems();
    }//GEN-LAST:event_jRadioButton_cumFreActionPerformed

    private void jCheckBox_YLogMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCheckBox_YLogMouseClicked
    {//GEN-HEADEREND:event_jCheckBox_YLogMouseClicked
         this.defaultSchema.isYAxisLogStyle = this.jCheckBox_YLog.isSelected();
    }//GEN-LAST:event_jCheckBox_YLogMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_item;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JCheckBox jCheckBox_XLog;
    private javax.swing.JCheckBox jCheckBox_YLog;
    private javax.swing.JCheckBox jCheckBox_lineSmooth;
    private javax.swing.JComboBox jComboBox_style;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_axisColor;
    private javax.swing.JLabel jLabel_fillColor;
    private javax.swing.JLabel jLabel_lineColor;
    private javax.swing.JPanel jPanel_items;
    private javax.swing.JRadioButton jRadioButton_cumFre;
    private javax.swing.JRadioButton jRadioButton_fre;
    private javax.swing.JSpinner jSpinner_axisWidth;
    private javax.swing.JSpinner jSpinner_dotRadius;
    private javax.swing.JSpinner jSpinner_lineWidth;
    // End of variables declaration//GEN-END:variables
}
